### PR TITLE
Manage none special preset

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes https://github.com/Soullivaneuh/styleci-fixers/issues/13

@jaydiablo Could you please test it and tell me if this works fine for you?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I might add a config validation endpoint to our API so you can check if config files are valid. Could be useful for watching for changes.

**Comment by Soullivaneuh** [comment]
> I might add a config validation endpoint to our API so you can check if config files are valid.

You mean pass the `.styleci.yml` content too validate it? On the bridge directly?

Not sure to understand, this will require an internet connection.

I think you are thinking for Travis. In that case, can you please elaborate?

**Comment by GrahamCampbell** [comment]
As a useful way to check that your sample config files are still valid according to our definition. We do sometimes make breaking changes.

**Comment by Soullivaneuh** [comment]
Oh yes, it will be very welcomed! :+1:

**Comment by GrahamCampbell** [comment]
Added to the API and SDK. I've been super lazy with the SDK though. Just expect guzzle to raise a bad request exception if the config is invalid.

**Comment by GrahamCampbell** [comment]
You can see the error json format at: https://api.styleci.io/validate.

**Comment by Soullivaneuh** [comment]
Wow, that was fast! Thanks!

I'll open an issue as a reminder.

BTW, do you have any online doc for your API?

**Comment by GrahamCampbell** [comment]
> BTW, do you have any online doc for your API?

Not yet sorry. It's so small, you can just read the entire SDK. It fits onto one screen at once. :P

**Comment by Soullivaneuh** [comment]
> It's so small, you can just read the entire SDK. It fits onto one screen at once. :P

That's not an excuse! :trollface: :wink:

**Comment by jaydiablo** [comment]
@Soullivaneuh I tested a .styleci.yml file with this content:

```yml
preset: none

enabled:
  - braces
  - duplicate_semicolon
  - elseif
  - empty_return
  - encoding
  - eof_ending
  - function_call_space
  - function_declaration
  - indentation
  - join_function
  - line_after_namespace
  - linefeed
  - lowercase_keywords
  - parenthesis
  - multiple_use
  - method_argument_space
  - object_operator
  - php_closing_tag
  - remove_lines_between_uses
  - short_array_syntax
  - short_tag
  - standardize_not_equal
  - trailing_spaces
  - unused_use
  - visibility
  - whitespacy_lines
```
(which validated fine in the styleic.io UI) And the php-cs-fixer bridge processed it fine.

Thanks!

**Comment by Soullivaneuh** [comment]
Thank you @jaydiablo for the report and the test. :+1:

**Comment by Soullivaneuh** [comment]
https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/releases/tag/v2.1.0

**Pull request merged**
