### PR TITLE
Use config platform to check php compatibility

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@GrahamCampbell this is not working. PHPUnit 5.0 is still added on requirements:

https://travis-ci.org/Soullivaneuh/php-cs-fixer-styleci-bridge/jobs/83450934#L116

**Comment by GrahamCampbell** [comment]
Looks like bug in composer then.

**Comment by GrahamCampbell** [comment]
Composer's require command should be able to deal with that without messing up.

**Comment by Soullivaneuh** [comment]
@Seldaek what do you think about this? Can you give a us a clue?

**Pull request closed without merging**
