### PR TITLE
Lock PHPUnit 4

### PR DESCRIPTION
**Pull request by Soullivaneuh**
For Travis working.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Better to use the platform config like composer does.

**Comment by GrahamCampbell** [comment]
That way you can force dependency installs to work on older versions of php.

**Comment by Soullivaneuh** [comment]
PHPUnit 5 does not support PHP<5.6 and may broke with older versions.

**Comment by GrahamCampbell** [comment]
I know. If you set that platform restriction, composer MUST use 4.x when you run the require command.

**Comment by GrahamCampbell** [comment]
Example: https://github.com/StyleCI/StyleCI/commit/e6a6086ce98c8f661c285475fe8b2799dd32081c.

**Comment by GrahamCampbell** [comment]
That means that if you run composer on php 7, you know the dependencies loaded will work on php 5.6 too.

**Comment by GrahamCampbell** [comment]
Useful when working with lock files.

**Comment by Soullivaneuh** [comment]
> Example: StyleCI/StyleCI@e6a6086.

I don't understand what this do. This force composer to check version agains php 5.6?

Well, problem still the same: PHPUnit 5 will be installed but will run on an unsupported **real** version and may crash.

**Comment by GrahamCampbell** [comment]
You'd want to use 5.3.3 or something, not what I used.

**Comment by GrahamCampbell** [comment]
Composer will have to pull in phpunit 4, not phpunit 5, because phpinit 5 says it doesnt support php 5.3 to composer.

**Comment by Soullivaneuh** [comment]
I see. But ou have to set it on the composer.json file. How to make it generic for Travis?

**Comment by GrahamCampbell** [comment]
Setting it in the composer.json is fine though? You want to know that all your dependencies are actually installable on 5.3.3.

**Comment by GrahamCampbell** [comment]
It doesn't affect anyone requiring your package - they can still require packages that don't work on 5.3.3.

**Comment by GrahamCampbell** [comment]
A bit like require-dev doesn't affect this package being required by other people.

**Comment by Soullivaneuh** [comment]
Because if I set `5.3.3`, it will install phpunit 4 for php 5.6.5 Would be better.

I know this is not better than my solution. :-P

But interactive configuration when running Travis before `composer up` should do the trick. Will try it.

**Pull request merged**
