### PR TITLE
use friendsofphp/php-cs-fixer instead of fabpot/php-cs-fixer

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is not correct. The package name as NOT changed for 1.x.

**Comment by OskarStark** [comment]
really? but it is working:

https://packagist.org/packages/friendsofphp/php-cs-fixer

and i saw it as a suggestion in composer output

**Comment by OskarStark** [comment]
bildschirmfoto 2016-05-31 um 16 46 17

**Comment by Soullivaneuh** [comment]
Indeed, the old version are accessible: https://packagist.org/packages/friendsofphp/php-cs-fixer#v1.6.1

The change only on 2.x is the namespace usage which is handled here: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/61/files

**Comment by Soullivaneuh** [comment]
Thank you @OskarStark :+1:

**Comment by GrahamCampbell** [comment]
> This package is abandoned and no longer maintained. The author suggests using the friendsofphp/php-cs-fixer package instead.

That was actually a mistake. They only meant to do that once 2.x has been released.

**Comment by GrahamCampbell** [comment]
You should use the old package name for 1.x, or you risk installing the package twice...

**Comment by Soullivaneuh** [comment]
> You should use the old package name for 1.x, or you risk installing the package twice...

What do you mean? How this could be possible?

On a fresh composer project:

```bash
sullivan@sweetnexy:~/tmp/cs-fixer$ composer require friendsofphp/php-cs-fixer:^1.6
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing symfony/stopwatch (v3.1.0)
    Loading from cache

  - Installing symfony/process (v3.1.0)
    Loading from cache

  - Installing symfony/finder (v3.1.0)
    Loading from cache

  - Installing symfony/filesystem (v3.1.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v3.1.0)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v3.1.0)
    Loading from cache

  - Installing friendsofphp/php-cs-fixer (v1.11.3)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files
```

So what is the problem?

**Comment by Soullivaneuh** [comment]
Also tried with `1.6.*`:

```bash
$ composer require 'friendsofphp/php-cs-fixer:1.6.*'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing symfony/stopwatch (v2.8.6)
    Downloading: 100%         

  - Installing symfony/process (v2.8.6)
    Loading from cache

  - Installing symfony/finder (v2.8.6)
    Loading from cache

  - Installing symfony/filesystem (v2.8.6)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.6)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.6)
    Loading from cache

  - Installing friendsofphp/php-cs-fixer (v1.6.2)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files
```

@GrahamCampbell I don't see how the package could be downloaded twice...

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell I don't see how the package could be downloaded twice...

Install friendsofphp/php-cs-fixer package and your bridge with the new dep.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Ok:

```bash
sullivan@sweetnexy:~/tmp/cs-fixer$ cat composer.json 
{
    "name": "root/cs-fixer",
    "authors": [
        {
            "name": "Sullivan SENECHAL",
            "email": "soullivaneuh@gmail.com"
        }
    ],
    "require": {
        "friendsofphp/php-cs-fixer": "1.6.*",
        "sllh/php-cs-fixer-styleci-bridge": "^2.0"
    }
}
sullivan@sweetnexy:~/tmp/cs-fixer$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing symfony/stopwatch (v2.8.6)
    Loading from cache

  - Installing symfony/process (v2.8.6)
    Loading from cache

  - Installing symfony/finder (v2.8.6)
    Loading from cache

  - Installing symfony/filesystem (v2.8.6)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.6)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.6)
    Loading from cache

  - Installing friendsofphp/php-cs-fixer (v1.6.2)
    Loading from cache

  - Installing sllh/styleci-fixers (v4.2.0)
    Loading from cache

  - Installing composer/semver (1.4.0)
    Loading from cache

  - Installing symfony/dependency-injection (v3.1.0)
    Loading from cache

  - Installing symfony/config (v3.1.0)
    Loading from cache

  - Installing symfony/yaml (v3.1.0)
    Loading from cache

  - Installing sllh/php-cs-fixer-styleci-bridge (v2.0.1)
    Loading from cache

symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing psr/log (For using the console logger)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
Writing lock file
Generating autoload files
```

No twice download of php-cs-fixer. And I didn't release this PR yet.

**Comment by Soullivaneuh** [comment]
Also tried this:

```bash
sullivan@sweetnexy:~/tmp/cs-fixer$ cat composer.json 
{
    "name": "root/cs-fixer",
    "authors": [
        {
            "name": "Sullivan SENECHAL",
            "email": "soullivaneuh@gmail.com"
        }
    ],
    "require": {
        "friendsofphp/php-cs-fixer": "1.6.*",
        "sllh/php-cs-fixer-styleci-bridge": "dev-master"
    }
}
sullivan@sweetnexy:~/tmp/cs-fixer$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sllh/styleci-fixers (v4.2.0)
    Loading from cache

  - Installing composer/semver (1.4.0)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.6)
    Loading from cache

  - Installing symfony/dependency-injection (v3.1.0)
    Loading from cache

  - Installing symfony/filesystem (v2.8.6)
    Loading from cache

  - Installing symfony/config (v3.1.0)
    Loading from cache

  - Installing symfony/yaml (v3.1.0)
    Loading from cache

  - Installing sllh/php-cs-fixer-styleci-bridge (dev-master d16004b)
    Cloning d16004bbd14e6667c418f3d23530ece26fb1e06b

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing symfony/stopwatch (v2.8.6)
    Loading from cache

  - Installing symfony/process (v2.8.6)
    Loading from cache

  - Installing symfony/finder (v2.8.6)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.6)
    Loading from cache

  - Installing friendsofphp/php-cs-fixer (v1.6.2)
    Loading from cache

symfony/console suggests installing psr/log (For using the console logger)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files
```

And this:

```bash
sullivan@sweetnexy:~/tmp/cs-fixer$ cat composer.json 
{
    "name": "root/cs-fixer",
    "authors": [
        {
            "name": "Sullivan SENECHAL",
            "email": "soullivaneuh@gmail.com"
        }
    ],
    "require": {
        "fabpot/php-cs-fixer": "1.6.*",
        "sllh/php-cs-fixer-styleci-bridge": "dev-master"
    }
}
sullivan@sweetnexy:~/tmp/cs-fixer$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sllh/styleci-fixers (v4.2.0)
    Loading from cache

  - Installing composer/semver (1.4.0)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.6)
    Loading from cache

  - Installing symfony/dependency-injection (v3.1.0)
    Loading from cache

  - Installing symfony/filesystem (v2.8.6)
    Loading from cache

  - Installing symfony/config (v3.1.0)
    Loading from cache

  - Installing symfony/yaml (v3.1.0)
    Loading from cache

  - Installing sllh/php-cs-fixer-styleci-bridge (dev-master d16004b)
    Cloning d16004bbd14e6667c418f3d23530ece26fb1e06b

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing symfony/stopwatch (v2.8.6)
    Loading from cache

  - Installing symfony/process (v2.8.6)
    Loading from cache

  - Installing symfony/finder (v2.8.6)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.6)
    Loading from cache

  - Installing fabpot/php-cs-fixer (v1.6.2)
    Loading from cache

symfony/console suggests installing psr/log (For using the console logger)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files
```

For the last case, the old name is prefered, but not twice download.

**Comment by Soullivaneuh** [comment]
@GrahamCampbell I'm waiting for your answer before releasing a new tag.

If you can find a concrete case causing problem, I'll remove this PR commit. :+1:

**Comment by GrahamCampbell** [comment]
> Also tried this:

Please try using the old name, and the dev-master for this package.

**Comment by GrahamCampbell** [comment]
Actually, quickly run `composer clear-cache`, then try again with no vendor folder or composer.lock. If that works, I'm convinced. Composer must have got cleverer. ;)

**Comment by Soullivaneuh** [comment]
```bash
sullivan@sweetnexy:~/tmp/cs-fixer$ cat composer.json 
{
    "require": {
        "fabpot/php-cs-fixer": "^1.11",
        "sllh/php-cs-fixer-styleci-bridge": "dev-master"
    }
}
sullivan@sweetnexy:~/tmp/cs-fixer$ rm -rf vendor/ composer.lock
sullivan@sweetnexy:~/tmp/cs-fixer$ composer clear-cache
Clearing cache (cache-dir): /home/sullivan/.composer/cache
Clearing cache (cache-files-dir): /home/sullivan/.composer/cache/files
Clearing cache (cache-repo-dir): /home/sullivan/.composer/cache/repo
Clearing cache (cache-vcs-dir): /home/sullivan/.composer/cache/vcs
All caches cleared.
sullivan@sweetnexy:~/tmp/cs-fixer$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sllh/styleci-fixers (v4.2.0)
    Downloading: 100%         

  - Installing composer/semver (1.4.0)
    Downloading: 100%         

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Downloading: 100%         

  - Installing symfony/console (v2.8.6)
    Downloading: 100%         

  - Installing symfony/dependency-injection (v3.1.0)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.8.6)
    Downloading: 100%         

  - Installing symfony/config (v3.1.0)
    Downloading: 100%         

  - Installing symfony/yaml (v3.1.0)
    Downloading: 100%         

  - Installing sllh/php-cs-fixer-styleci-bridge (dev-master d16004b)
    Cloning d16004bbd14e6667c418f3d23530ece26fb1e06b

  - Installing sebastian/diff (1.4.1)
    Downloading: 100%         

  - Installing symfony/stopwatch (v2.8.6)
    Downloading: 100%         

  - Installing symfony/process (v2.8.6)
    Downloading: 100%         

  - Installing symfony/finder (v2.8.6)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v2.8.6)
    Downloading: 100%         

  - Installing fabpot/php-cs-fixer (v1.6.2)
    Downloading: 100%         

symfony/console suggests installing psr/log (For using the console logger)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files
```

@GrahamCampbell Convinced now? :trollface: :wink:

**Comment by GrahamCampbell** [comment]
Yeh. :P

**Pull request merged**
