### PR TITLE
Manage aliases

### LINKED ISSUE #13: Manage aliases
https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/blob/dc7535933df0dab296e2df0d21c6be18a764b519/src/StyleCI/Fixers.php#L374

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #13.

Adds both aliases and real fixers if set. PHP-CS-Fixer would not take care if not existing.

Better compatibility between PHP-CS-Fixer 1.x and 2.x.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> Better compatibility between PHP-CS-Fixer 1.x and 2.x.

Maybe it's best to register both versions of the fixer, so this bridge can work on both 1.x and 2.x?

**Comment by GrahamCampbell** [comment]
At least for now, 2.x won't throw an exception for an invalid fixer name.

**Comment by GrahamCampbell** [comment]
And 1.x never did, and never will. :)

**Comment by Soullivaneuh** [comment]
> Maybe it's best to register both versions of the fixer

That is the goal of `resolveAliases`. :+1: 

> At least for now, 2.x won't throw an exception for an invalid fixer name.

Doh, so my solution won't work properly...

Aliases is for 1.x version of php-cs-fixer isn't it? In this case, I would only resolve for 2.x -> 1.x, not the reverse.

Or, find a way to use PHP-CS-Fixer code to remove fixer that is not existing after the manual resolving...

**Comment by GrahamCampbell** [comment]
Well, for now, you have a hard dependency on the original php-cs-fixer and 1.x, so you don't really need to worry about anything else?

**Comment by Soullivaneuh** [comment]
The hard dependency is just here on require-dev to access PHP-CS-Fixer class and test it later.

BTW, I set up a job for 2.x too: https://travis-ci.org/Soullivaneuh/php-cs-fixer-styleci-bridge/jobs/82129654

**Comment by GrahamCampbell** [comment]
Right. :)

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Just tested php-cs-fixer with a fake fixer, no error thrown.

Where did you see that?

**Comment by Soullivaneuh** [comment]
Oh, I misread your setence!

> At least for now, 2.x **won't** throw an exception for an invalid fixer name.

So it's OK for now! :tada:

**Comment by Soullivaneuh** [comment]
@GrahamCampbell Now it does...

```bash
$ make cs
php-cs-fixer fix --verbose
                               
  [UnexpectedValueException]   
  Rule "psr4" does not exist.  
```

**Pull request merged**
