### PR TITLE
allow Symfony 3.0

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
PHP-CS-FIXER doesn't allow symfony 3 yet.

**Comment by lsmith77** [comment]
sigh .. how annoying
well will drop this repo then down to suggest
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1188

**Comment by Soullivaneuh** [comment]
> PHP-CS-FIXER doesn't allow symfony 3 yet.

Is that a problem? I mean, this bridge can already accept SF 3.0 components before PHP-CS-fixer accept it.

BTW, it would be nice to propose a PR on PHP-CS-Fixer to allow SF 3.

**Comment by Soullivaneuh** [comment]
@lsmith77 Did you test it with SF3?

**Comment by Soullivaneuh** [comment]
> PHP-CS-FIXER doesn't allow symfony 3 yet.
> > Is that a problem? I mean, this bridge can already accept SF 3.0 components before PHP-CS-fixer accept it.

Ok I just realized why. :-)

So yes, but it's a dev dependencies. Maybe we could accept it and force it on Travis for test.

**Comment by Soullivaneuh** [comment]
Just tested on SF3, works for now. Going to merge, thanks @lsmith77.

**Pull request merged**
