### PR TITLE
Allow symfony 4

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
Sorry for the new branch, but i had some remote link chaos.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
but now it should work.

**Comment by ElectricMaxxx** [comment]
@Soullivaneuh i tried to use `2.8` of `php-cs-fixer`, which allows symfony 4.0. But then a lot of more issues came into the scene. What to do now? PR to support Symfony 4.0 on 1.x in php-cs-fixer? What do you think?

**Comment by Soullivaneuh** [comment]
Ref old PR: #81

> What to do now? PR to support Symfony 4.0 on 1.x in php-cs-fixer? What do you think?

Sadly I don't really know right now. StyleCI configuration is now very diverged from php-cs-fixer 2.x, that makes the compatibility hard to do.

See #79 and https://github.com/Soullivaneuh/styleci-fixers/pull/14

Do you have anything to suggest?

Using the 1.x version as a .phar didn't solve this?

**Comment by ElectricMaxxx** [comment]
Then lets try to do an PR against 1.x of php-cs-fixer first.

**Comment by ElectricMaxxx** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3288

**Comment by ElectricMaxxx** [comment]
Caused by the answer in the PR, i started a try to use the phar in your system. But i am completley lost. Doing so i would need a lot of help, or you should do it as i have no experience with you code base. Or you should update the library to use 2.x only and release the symony support on a new major.

**Comment by ElectricMaxxx** [comment]
Will close that as sonata-project removes this package now.

**Pull request closed without merging**
